 ##This is a onfiguration file to set up the virtual machines with the appropriate packages and modules
##for the cloud class.

---
- name: Config Web VM with Docker and Apps
  hosts: webservers
  become: true
  tasks:

     - name: docker.io

       apt:
         update_cache: yes
         name: docker.io
         state: present

     - name: Install pip3

       apt:
         force_apt_get: yes
         name: python3-pip
         state: present

     - name: Install Python Docker module
       pip:
         name: docker
         state: present

     - name: Download and launch docker web container

       docker_container:
         name: dvwa
         image: cyberxsecurity/dvwa
         state: started
         restart_policy: always
         published_ports: 80:80

     - name: Enable docker service
       systemd:
         name: docker
         enabled: yes

     - name: Enable docker service
       systemd:
         name: docker
         enabled: yes